services:
  - type: web
    name: infosys-spy
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: SONAR_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
